"""introduces metrics tables

Revision ID: 0e83df78007e
Revises: 34b2e3d4948f
Create Date: 2023-11-22 14:56:26.070441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e83df78007e'
down_revision = '34b2e3d4948f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_issue',
    sa.Column('issue_id', sa.String(length=32), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_index(op.f('ix_newsletter_issue_issue_id'), 'newsletter_issue', ['issue_id'], unique=False)
    op.create_table('issue_article',
    sa.Column('issue_id', sa.String(length=32), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['newsletter_issue.issue_id'], ),
    sa.PrimaryKeyConstraint('issue_id', 'article_id')
    )
    op.create_table('issue_metrics',
    sa.Column('metrics_id', sa.String(length=32), nullable=False),
    sa.Column('newsletter_generation_config_id', sa.Integer(), nullable=False),
    sa.Column('time_to_generate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['metrics_id'], ['newsletter_issue.issue_id'], ),
    sa.ForeignKeyConstraint(['newsletter_generation_config_id'], ['newsletter_generation_config.id'], ),
    sa.PrimaryKeyConstraint('metrics_id')
    )
    op.create_table('token_cost',
    sa.Column('token_cost_id', sa.Integer(), nullable=False),
    sa.Column('metrics_id', sa.String(length=32), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['metrics_id'], ['issue_metrics.metrics_id'], ),
    sa.PrimaryKeyConstraint('token_cost_id')
    )
    op.create_index(op.f('ix_token_cost_token_cost_id'), 'token_cost', ['token_cost_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_cost_token_cost_id'), table_name='token_cost')
    op.drop_table('token_cost')
    op.drop_table('issue_metrics')
    op.drop_table('issue_article')
    op.drop_index(op.f('ix_newsletter_issue_issue_id'), table_name='newsletter_issue')
    op.drop_table('newsletter_issue')
    # ### end Alembic commands ###
