"""adds response attribute to the relevancy_prompt table

Revision ID: 1b9281d96222
Revises: c8e30091928b
Create Date: 2024-01-24 12:08:31.730669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9281d96222'
down_revision = 'c8e30091928b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relevancy_prompt',
    sa.Column('issue_id', sa.String(length=32), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('response', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['newsletter_issue.issue_id'], ),
    sa.PrimaryKeyConstraint('issue_id', 'article_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relevancy_prompt')
    # ### end Alembic commands ###
