"""introduces redundancy_prompt table

Revision ID: 24ececcacb62
Revises: a2e31e88c7a2
Create Date: 2024-01-24 10:52:17.885180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ececcacb62'
down_revision = 'a2e31e88c7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redundancy_prompt',
    sa.Column('issue_id', sa.String(length=32), nullable=False),
    sa.Column('current_article_id', sa.String(length=36), nullable=False),
    sa.Column('previous_article_id', sa.String(length=36), nullable=False),
    sa.Column('response', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['newsletter_issue.issue_id'], ),
    sa.PrimaryKeyConstraint('issue_id', 'current_article_id', 'previous_article_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('redundancy_prompt')
    # ### end Alembic commands ###
