"""adds the models to newsletter creator config

Revision ID: 34b2e3d4948f
Revises: a10a588263ab
Create Date: 2023-11-21 12:52:54.589740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b2e3d4948f'
down_revision = 'a10a588263ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newslettergenerationconfig', sa.Column('min_description_len_for_evaluation_prompts', sa.Integer(), nullable=True))
    op.add_column('newslettergenerationconfig', sa.Column('text_generation_model', sa.String(), nullable=True))
    op.add_column('newslettergenerationconfig', sa.Column('decision_model', sa.String(), nullable=True))
    op.drop_column('newslettergenerationconfig', 'min_article_description_to_consider_for_article_evaluation_prom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newslettergenerationconfig', sa.Column('min_article_description_to_consider_for_article_evaluation_prom', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('newslettergenerationconfig', 'decision_model')
    op.drop_column('newslettergenerationconfig', 'text_generation_model')
    op.drop_column('newslettergenerationconfig', 'min_description_len_for_evaluation_prompts')
    # ### end Alembic commands ###
