"""Initial migration

Revision ID: 3aec957f5c14
Revises: d4867f3a4c0a
Create Date: 2023-08-11 12:23:35.797035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3aec957f5c14"
down_revision = "d4867f3a4c0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("search_term", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscription_id"), "subscription", ["id"], unique=False)
    op.drop_constraint("item_owner_id_fkey", "item", type_="foreignkey")
    op.drop_column("item", "owner_id")
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.add_column(
        "item", sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key("item_owner_id_fkey", "item", "user", ["owner_id"], ["id"])
    op.drop_index(op.f("ix_subscription_id"), table_name="subscription")
    op.drop_table("subscription")
    # ### end Alembic commands ###
