"""adds sample_available field to Subscription

Revision ID: 48626c8e793d
Revises: 63c7c9f8175c
Create Date: 2023-11-12 18:29:31.011136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48626c8e793d'
down_revision = '63c7c9f8175c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('sample_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'sample_available')
    # ### end Alembic commands ###
