"""removes User subscription search tracking

Revision ID: 63c7c9f8175c
Revises: dbdfa143b088
Create Date: 2023-10-22 10:51:55.895964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c7c9f8175c'
down_revision = 'dbdfa143b088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'max_subscription_search_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('max_subscription_search_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
