"""message

Revision ID: 8c49390b7647
Revises: 98604827a4c3
Create Date: 2023-08-19 13:01:41.243256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c49390b7647'
down_revision = '98604827a4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
