"""adds subscription limit info to User

Revision ID: 98604827a4c3
Revises: 3aec957f5c14
Create Date: 2023-08-18 13:07:41.071853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "98604827a4c3"
down_revision = "3aec957f5c14"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("last_subscription_search_timestamp", sa.Integer(), nullable=True),
    )
    op.add_column(
        "user", sa.Column("subscription_search_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "user", sa.Column("max_subscription_search_count", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "max_subscription_search_count")
    op.drop_column("user", "subscription_search_count")
    op.drop_column("user", "last_subscription_search_timestamp")
    # ### end Alembic commands ###
