"""adds newsletter generation config table

Revision ID: a10a588263ab
Revises: 48626c8e793d
Create Date: 2023-11-21 10:35:33.549552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10a588263ab'
down_revision = '48626c8e793d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newslettergenerationconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary_prompt', sa.String(), nullable=True),
    sa.Column('summary_max_word_count', sa.Integer(), nullable=True),
    sa.Column('min_article_description_to_consider_for_article_evaluation_prompts_instead_of_article_summary', sa.Integer(), nullable=True),
    sa.Column('article_redundancy_prompt', sa.String(), nullable=True),
    sa.Column('article_relevancy_prompt', sa.String(), nullable=True),
    sa.Column('newsletter_subject_prompt', sa.String(), nullable=True),
    sa.Column('max_articles_per_newsletter', sa.Integer(), nullable=True),
    sa.Column('max_processed_articles_per_newsletter', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newslettergenerationconfig_id'), 'newslettergenerationconfig', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_newslettergenerationconfig_id'), table_name='newslettergenerationconfig')
    op.drop_table('newslettergenerationconfig')
    # ### end Alembic commands ###
