"""introduces news newsletter creator config var

Revision ID: a2e31e88c7a2
Revises: 0e83df78007e
Create Date: 2023-11-23 09:32:47.698567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e31e88c7a2'
down_revision = '0e83df78007e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletter_generation_config', sa.Column('articles_qualifier_prompt', sa.String(), nullable=True))
    op.add_column('subscription', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'is_active')
    op.drop_column('newsletter_generation_config', 'articles_qualifier_prompt')
    # ### end Alembic commands ###
