"""adjust issue_metrics.newsletter_generation_config_id

Revision ID: bbe90972c9e3
Revises: 745af60014f6
Create Date: 2023-11-22 13:53:06.210049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe90972c9e3'
down_revision = '745af60014f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
