"""introduces relevancy_prompt table

Revision ID: c8e30091928b
Revises: 24ececcacb62
Create Date: 2024-01-24 11:01:00.988996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e30091928b'
down_revision = '24ececcacb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
