"""several DB changes for the app rework

Revision ID: dbdfa143b088
Revises: e0a10cfea046
Create Date: 2023-10-22 10:47:00.355494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdfa143b088'
down_revision = 'e0a10cfea046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscription_search_count')
    op.drop_column('user', 'last_subscription_search_timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_subscription_search_timestamp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('subscription_search_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
