"""update Subscription attributei again

Revision ID: e0a10cfea046
Revises: eeec36c072c4
Create Date: 2023-09-14 15:15:11.424554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e0a10cfea046"
down_revision = "eeec36c072c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription", sa.Column("newsletter_description", sa.String(), nullable=True)
    )
    op.drop_column("subscription", "search_description")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription",
        sa.Column(
            "search_description", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("subscription", "newsletter_description")
    # ### end Alembic commands ###
