"""update Subscription attribute

Revision ID: eeec36c072c4
Revises: 2da15850c3c9
Create Date: 2023-09-14 15:08:03.187172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eeec36c072c4"
down_revision = "2da15850c3c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription", sa.Column("search_description", sa.String(), nullable=True)
    )
    op.drop_column("subscription", "search_term")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription",
        sa.Column("search_term", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("subscription", "search_description")
    # ### end Alembic commands ###
