"""fixes foreign references

Revision ID: ef0bbbbc6782
Revises: bbe90972c9e3
Create Date: 2023-11-22 14:04:03.491258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0bbbbc6782'
down_revision = 'bbe90972c9e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
